### PR TITLE
Feature branch

### PR DESCRIPTION
**Pull request by kotoku-code**
## Bubble-sort 
- used sort algorithm with ruby
- Added stickler, gem and rubocop
- Added Readme file

Thank you for reviewing are code, kindly let us know and feed-back you may have and we will work to correct it.

kind regards,

### CODE REVIEW

**Review by MauricioRobayo — CHANGES_REQUESTED** [review]
Very nice project!

It looks great and is coming into place, but please double-check:

* [x] Please fix Stickler issues.
* [x] `bubble_sort_by` is missing ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_bubble_sort/sortBy.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-1)).

Status: __Request changes__.

**Comment by Luckyaremu** [comment]
Bubble-sort
-bubble_sort_by fixed
-stickler errors fixed
Thank you for reviewing are code, kindly let us know any feed-back you may have and we will work to correct it.

kind regards,

**Review by MauricioRobayo — CHANGES_REQUESTED** [review]
Good work, it is looking great so far, but please double-check the following issues:

* [ ] Rubocop is reporting some offenses:

<details>
 <summary><code>$ rubocop bubble_sort.rb</code></summary>
<pre><code>
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file:
 - Style/HashEachMethods (0.80)
 - Style/HashTransformKeys (0.80)
 - Style/HashTransformValues (0.80)
For more information: https://docs.rubocop.org/en/latest/versioning/
Inspecting 1 file
C

Offenses:

bubble_sort.rb:7:34: C: Style/Semicolon: Do not use semicolons to terminate expressions.
    (arr.length - 1).times do |i|;
                                 ^
bubble_sort.rb:8:7: C: Style/Next: Use next to skip iteration.
      if arr[i] > arr[i + 1]
      ^^^^^^^^^^^^^^^^^^^^^^

1 file inspected, 2 offenses detected
</code></pre>
</details>

* [ ] Something happened to Stickler, we need to see the green checkmark on the last commit submitted - abb90fd - https://github.com/Luckyaremu/bubble_sort/pull/1/checks.

Status: __Request changes__.

---

Optional: You could remove all debugging/testing from the source code and place it on the README.md or a different file as tests/examples. This helps to separate logic form user interface, also makes it easier to work with without unnecessary noise from debugging/test cases.

**Comment by kotoku-code** [comment]
-please note from the image that the stickler is enabled

-stickler errors fixed

**Comment by kotoku-code** [comment]
linters

**Review by MauricioRobayo — APPROVED** [review]
Well done!

The project looks great and all requirements are met.

Some times Stickler is a weird thing, I double-checked your linters configuration and there are no Rubocop offenses, so it is a 👍 from me.

Status: __Approved__.

Optional: You could remove all debugging/testing from the source code and place it on the README.md or a different file as tests/examples. This helps to separate logic form user interface, also makes it easier to work with without unnecessary noise from debugging/test cases.

**Pull request merged**
